# Generated by Django 5.1.4 on 2025-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('rating', models.FloatField(default=5)),
                ('image_path', models.CharField(default='static/img/dinh-doc-lap.jpg', max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
