# Generated by Django 5.1.4 on 2025-06-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TemporaryTripCart',
        ),
        migrations.DeleteModel(
            name='TemporaryUser',
        ),
    ]
