# Generated by Django 5.1.4 on 2025-04-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='open_hours',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='ticket_info',
            field=models.CharField(default='', max_length=30),
        ),
    ]
