# Generated by Django 5.1.4 on 2025-05-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_temporaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippath',
            name='locations',
            field=models.ManyToManyField(related_name='trip_paths', to='location.location'),
        ),
    ]
