# Generated by Django 5.1.4 on 2025-05-18 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_trippath_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippath',
            name='end_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_paths', to='location.location'),
        ),
        migrations.AddField(
            model_name='trippath',
            name='start_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_paths', to='location.location'),
        ),
    ]
