# Generated by Django 5.1.4 on 2025-04-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_open_hours_location_ticket_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=32),
        ),
    ]
