# Generated by Django 5.1.4 on 2025-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_location_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('loclist', models.ManyToManyField(blank=True, related_name='users', to='location.location')),
            ],
        ),
    ]
