# Generated by Django 5.1.4 on 2025-04-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coordinate',
            field=models.CharField(default='', max_length=40),
        ),
    ]
