# Generated by Django 5.1.4 on 2025-04-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loclist',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to='location.location'),
        ),
    ]
