# Generated by Django 5.1.4 on 2025-04-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_alter_location_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='long_description',
            field=models.TextField(default=''),
        ),
    ]
