# Generated by Django 5.1.4 on 2025-04-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_location_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.AlterField(
            model_name='location',
            name='image_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
