# Generated by Django 5.1.4 on 2025-04-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_remove_location_city_alter_location_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
