# Generated by Django 5.1.4 on 2025-04-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_alter_location_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('accomodation', 'Accommodation'), ('entertainment', 'Entertainment'), ('f&B', 'F&B'), ('local', 'Local'), ('market', 'Market')], max_length=13),
        ),
    ]
