# Generated by Django 5.1.4 on 2025-04-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_alter_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='ticket_info',
            field=models.CharField(default='', max_length=64),
        ),
    ]
