# Generated by Django 5.1.4 on 2025-04-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_alter_location_address_alter_location_ticket_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='ticket_info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
