# Generated by Django 5.1.4 on 2025-04-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_alter_location_address_alter_location_ticket_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(default='', max_length=13),
        ),
    ]
