# Generated by Django 5.1.4 on 2025-04-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_triplist_trippath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triplist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='triplist',
            name='description',
        ),
        migrations.AlterField(
            model_name='triplist',
            name='name',
            field=models.CharField(default='My trip list', max_length=255),
        ),
    ]
