# Generated by Django 5.1.4 on 2025-04-29 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_remove_triplist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplist',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
