# Generated by Django 5.1.4 on 2025-04-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_alter_triplist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplist',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
