# Generated by Django 5.1.4 on 2025-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_alter_triplist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippath',
            name='total_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
