# Generated by Django 5.1.4 on 2025-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_trippath_total_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippath',
            name='locations_ordered',
            field=models.CharField(max_length=255),
        ),
    ]
