# Generated by Django 5.1.4 on 2025-05-03 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_alter_trippath_locations_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='open_hours',
        ),
        migrations.AddField(
            model_name='location',
            name='close_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name='location',
            name='open_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
