# Generated by Django 5.1.4 on 2025-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_remove_location_open_hours_location_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
