# Generated by Django 5.1.4 on 2025-05-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0024_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bot_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
