# Generated by Django 5.1.4 on 2025-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0026_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippath',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
