# Generated by Django 5.1.4 on 2025-05-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0028_alter_trippath_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippath',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
