# Generated by Django 5.1.4 on 2025-05-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0029_alter_trippath_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trippath',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
